### ISSUE TITLE
Reserved docker image tag doesn't exist

### ISSUE THREAD

**Issue by xingheng** [mcopik/FBACode#3]
I just tried to build the example project via the `builder.py` like below, the docker image `mcopik/fbacode` exists but not tag `ubuntu-2004-clang-11`, [the latest] one is [ubuntu-1804-clang-9](https://hub.docker.com/r/mcopik/fbacode/tags) pushed last two years, is that deleted? What should I use instead?

```
➜  FBACode git:(master) ✗ ./builder.py examples/github-repo.json --verbose
Opening config file build.cfg
Opening user config file user.cfg
submitted 1 tasks to queue
| builds_left	1
| SpawnProcess-2	(0, 'abseil/abseil-cpp')
INFO - [0/1] Clone abseil_abseil-cp repository from https://github.com/abseil/abseil-cpp to source/abseil_abseil-cp
INFO - [0/1] Cloned project abseil/abseil-cpp from GitHub in 0.001942 seconds
Failure in abseil/abseil-cpp builder:
404 Client Error: Not Found ("manifest for mcopik/fbacode:ubuntu-2004-clang-11 not found: manifest unknown: manifest unknown")
Exception trace:
Traceback (most recent call last):
  File "/Users/me/FBACode/fbacode-virtualenv/lib/python3.9/site-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/Users/me/FBACode/fbacode-virtualenv/lib/python3.9/site-packages/requests/models.py", line 1022, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.35/containers/create
```

**Comment by mcopik** [comment]
@xingheng thank you for rising this and the other issue! I'm out of the office this week and I will try to take a look as soon as possible.

We haven't used that code in a while and it's possible that some configurations and deployments are no longer valid.

**Comment by xingheng** [comment]
@mcopik Are you back? I tried to resolve the docker image name to the latest one `-1804-` but failed with more confusing errors. Maybe could we have another base available local dockerfile?

**Comment by mcopik** [comment]
@xingheng I pushed the missing Docker images, including the `mcopik/fbacode:ubuntu-2004-clang-11`. Apologies for the slow reply - we have a busy summer with paper resubmissions.

I hope it works - the project requires an update since the last major work was completed in early 2021. Unfortunately, we have been focused on other research projects, and I cannot estimate when we will be able to update FBACode.

If you still experience issues, then please feel free to reopen this issue or open a new one.
